package com.bookstore.common.enums;

public enum OrderStatus {

    PENDING,
    CONFIRMED,
    ORDER_CREATED,
    ORDER_FAILED, BOOK_RESERVED, PAYMENT_REQUESTED, BOOK_UNAVAILABLE, BOOK_RESERVATION_REQUESTED, PAYMENT_COMPLETED, PAYMENT_FAILED, ORDER_COMPLETED, BOOK_CONFIRMED, BOOK_REJECTED, DELIVERED, FAILED, REJECTED
}
